language: node_js
node_js:
  "node"

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: coverage
      script: npm run coveralls
    - stage: deploy_docs
      script: npm run doc
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: documentation/
        verbose: true
        on:
          branch: master

stages:
  - deploy_docs
  - test
  - coverage
  